version: '3'
services:
  nginx:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/conf:/etc/nginx/conf.d
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/dhparam:/etc/nginx/dhparam
      - ./data/certs:/etc/nginx/certs:ro
      - $DOCKER_HOST_PATH:/tmp/docker.sock:ro
    networks:
      - domains
    restart: always
    environment:
      HSTS: "off"

  local-certs:
    container_name: proxy-companion
    restart: always
    image: sebastienheyd/self-signed-proxy-companion
    volumes:
      - $DOCKER_HOST_PATH:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:rw
    environment:
      EXPIRATION: 396

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  domains:
    external: true
