version: '3'
services:
  nginx:
    image: nginxdemos/hello
    expose:
      - "80"
    networks:
      - domains
    environment:
      VIRTUAL_HOST: proxytestdemo.local
      SELF_SIGNED_HOST: proxytestdemo.local
      VIRTUAL_PORT: 80
    restart: no
networks:
  domains:
    external: true
